name: Generate Snake Game Animation

on:
  schedule:
    - cron: '0 0 * * *' # Это говорит о том, что действие будет выполняться ежедневно в полночь
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate snake game
      uses: Platane/snk@master
      with:
        github_user_name: Sergeypdf
        svg_out_path: dist/github-snake.svg

